// types/countries.ts
export enum CountryCode {
    GB = "United Kingdom",
    US = "United States",
    FR = "France",
    DE = "Germany",
    IR = "Iran",
    ES = "Spain",
    IT = "Italy",
    NL = "Netherlands",
    BE = "Belgium",
    PT = "Portugal",
    AT = "Austria",
    GR = "Greece",
    SE = "Sweden",
    DK = "Denmark",
    FI = "Finland",
    IE = "Ireland",
    LU = "Luxembourg",
    CY = "Cyprus",
    MT = "Malta",
    EE = "Estonia",
    LT = "Lithuania",
    LV = "Latvia",
    PL = "Poland",
    CZ = "Czech Republic",
    SK = "Slovakia",
    HU = "Hungary",
    SI = "Slovenia",
    RO = "Romania",
    BG = "Bulgaria",
    HR = "Croatia",
    RS = "Serbia",
    ME = "Montenegro",
    AL = "Albania",
    MK = "North Macedonia",
    BA = "Bosnia and Herzegovina",
    XK = "Kosovo",
    UA = "Ukraine",
    BY = "Belarus",
    MD = "Moldova",
    RU = "Russia",
    AM = "Armenia",
    AZ = "Azerbaijan",
    GE = "Georgia",
    KZ = "Kazakhstan",
    TJ = "Tajikistan",
    TM = "Turkmenistan",
    UZ = "Uzbekistan",
    TR = "Turkey",
    CN = "China",
    JP = "Japan",
    KR = "South Korea",
    VN = "Vietnam",
    IN = "India",
    PK = "Pakistan",
    BD = "Bangladesh",
    NP = "Nepal",
    LK = "Sri Lanka",
    MM = "Myanmar",
    TH = "Thailand",
    LA = "Laos",
    KH = "Cambodia",
    MY = "Malaysia",
    SG = "Singapore",
    ID = "Indonesia",
    TL = "Timor-Leste",
    PH = "Philippines",
    AU = "Australia",
    NZ = "New Zealand",
    FJ = "Fiji",
    TO = "Tonga",
    WS = "Samoa",
    TV = "Tuvalu",
    SB = "Solomon Islands",
    PG = "Papua New Guinea",
    NR = "Nauru",
    VU = "Vanuatu",
    NC = "New Caledonia",
    PF = "French Polynesia",
    CK = "Cook Islands",
    NU = "Niue",
    WF = "Wallis and Futuna",
    PN = "Pitcairn Islands",
    TK = "Tokelau",
    FM = "Micronesia",
    MH = "Marshall Islands",
    PW = "Palau",
    KP = "North Korea",

  }
  
  export enum CountryFlag {
    US = "🇺🇸",
    GB = "🇬🇧",
    FR = "🇫🇷",
    DE = "🇩🇪",
    IR = "🇮🇷",
    ES = "🇪🇸",
    IT = "🇮🇹",
    NL = "🇳🇱",
    BE = "🇧🇪",
    PT = "🇵🇹",
    AT = "🇦🇹",
    GR = "🇬🇷",
    SE = "🇸🇪",
    DK = "🇩🇰",
    FI = "🇫🇮",
    IE = "🇮🇪",
    LU = "🇱🇺",
    CY = "🇨🇾",
    MT = "🇲🇹",
    EE = "🇪🇪",
    LT = "🇱🇹",
    LV = "🇱🇻",
    PL = "🇵🇱",
    CZ = "🇨🇿",
    SK = "🇸🇰",
    HU = "🇭🇺",
    SI = "🇸🇮",
    RO = "🇷🇴",
    BG = "🇧🇬",
    HR = "🇭🇷",
    RS = "🇷🇸",
    ME = "🇲🇪",
    AL = "🇦🇱",
    MK = "🇲🇰",
    BA = "🇧🇦",
    XK = "🇽🇰",
    UA = "🇺🇦",
    BY = "🇧🇾",
    MD = "🇲🇩",
    RU = "🇷🇺",
    AM = "🇦🇲",
    AZ = "🇦🇿",
    GE = "🇬🇪",
    KZ = "🇰🇿",
    TJ = "🇹🇯",
    TM = "🇹🇲",
    UZ = "🇺🇿",
    TR = "🇹🇷",
    CN = "🇨🇳",
    JP = "🇯🇵",
    KR = "🇰🇷",
    VN = "🇻🇳",
    IN = "🇮🇳",
    PK = "🇵🇰",
    BD = "🇧🇩",
    NP = "🇳🇵",
    LK = "🇱🇰",
    MM = "🇲🇲",
    TH = "🇹🇭",
    LA = "🇱🇦",
    KH = "🇰🇭",
    MY = "🇲🇾",
    SG = "🇸🇬",
    ID = "🇮🇩",
    TL = "🇹🇱",
    PH = "🇵🇭",
    AU = "🇦🇺",
    NZ = "🇳🇿",
    FJ = "🇫🇯",
    TO = "🇹🇴",
    WS = "🇼🇸",
    TV = "🇹🇻",
    SB = "🇸🇧",
    PG = "🇵🇬",
    NR = "🇳🇷",
    VU = "🇻🇺",
    NC = "🇳🇨",
    PF = "🇵🇫",
    CK = "🇨🇰",
    NU = "🇳🇺",
    WF = "🇼🇫",
    PN = "🇵🇳",
    TK = "🇹🇰",
    FM = "🇫🇲",
    MH = "🇲🇭",
    PW = "🇵🇼",
    KP = "🇰🇵",

  }
  
  export enum CountryDialCode {
   GB = "+44",
    US = "+1",
    FR = "+33",
    DE = "+49",
    IR = "+98",
    ES = "+34",
    IT = "+39",
    NL = "+31",
    BE = "+32",
    PT = "+351",
    AT = "+43",
    GR = "+30",
    SE = "+46",
    DK = "+45",
    FI = "+358",
    IE = "+353",
    LU = "+352",
    CY = "+357",
    MT = "+356",
    EE = "+372",
    LT = "+370",
    LV = "+371",
    PL = "+48",
    CZ = "+420",
    SK = "+421",
    HU = "+36",
    SI = "+386",
    RO = "+40",
    BG = "+359",
    HR = "+385",
    RS = "+381",
    ME = "+382",
    AL = "+355",
    MK = "+389",
    BA = "+387",
    XK = "+383",
    UA = "+380",
    BY = "+375",
    MD = "+373",
    RU = "+7",
    AM = "+374",
    AZ = "+994",
    GE = "+995",
    KZ = "+7",
    TJ = "+992",
    TM = "+993",
    UZ = "+998",
    TR = "+90",
    CN = "+86",
    JP = "+81",
    KR = "+82",
    VN = "+84",
    IN = "+91",
    PK = "+92",
    BD = "+880",
    NP = "+977",
    LK = "+94",
    MM = "+95",
    TH = "+66",
    LA = "+856",
    KH = "+855",
    MY = "+60",
    SG = "+65",
    ID = "+62",
    TL = "+670",
    PH = "+63",
    AU = "+61",
    NZ = "+64",
    FJ = "+679",
    TO = "+676",
    WS = "+685",
    TV = "+688",
    SB = "+677",
    PG = "+675",
    NR = "+674",
    VU = "+678",
    NC = "+687",
    PF = "+689",
    CK = "+682",
    NU = "+683",
    WF = "+681",
    PN = "+870",
    TK = "+690",
    FM = "+691",
    MH = "+692",
    PW = "+680",
    KP = "+850",
  
  }
  
  export interface CountryPhone {
    name: CountryCode;
    dialCode: CountryDialCode;
    flag: CountryFlag;
  }
  
  export const countriesPhone: CountryPhone[] = [
    { name:CountryCode.GB, dialCode: CountryDialCode.GB, flag: CountryFlag.GB },
    { name:CountryCode.US, dialCode: CountryDialCode.US, flag: CountryFlag.US },
    { name:CountryCode.FR, dialCode: CountryDialCode.FR, flag: CountryFlag.FR },
    { name:CountryCode.DE, dialCode: CountryDialCode.DE, flag: CountryFlag.DE },
    { name:CountryCode.IR, dialCode: CountryDialCode.IR, flag: CountryFlag.IR },
    { name:CountryCode.ES, dialCode: CountryDialCode.ES, flag: CountryFlag.ES },
    { name:CountryCode.IT, dialCode: CountryDialCode.IT, flag: CountryFlag.IT },
    { name:CountryCode.NL, dialCode: CountryDialCode.NL, flag: CountryFlag.NL },
    { name:CountryCode.BE, dialCode: CountryDialCode.BE, flag: CountryFlag.BE },
    { name:CountryCode.PT, dialCode: CountryDialCode.PT, flag: CountryFlag.PT },
    { name:CountryCode.AT, dialCode: CountryDialCode.AT, flag: CountryFlag.AT },
    { name:CountryCode.GR, dialCode: CountryDialCode.GR, flag: CountryFlag.GR },
    { name:CountryCode.SE, dialCode: CountryDialCode.SE, flag: CountryFlag.SE },
    { name:CountryCode.DK, dialCode: CountryDialCode.DK, flag: CountryFlag.DK },
    { name:CountryCode.FI, dialCode: CountryDialCode.FI, flag: CountryFlag.FI },
    { name:CountryCode.IE, dialCode: CountryDialCode.IE, flag: CountryFlag.IE },
    { name:CountryCode.LU, dialCode: CountryDialCode.LU, flag: CountryFlag.LU },
    { name:CountryCode.CY, dialCode: CountryDialCode.CY, flag: CountryFlag.CY },
    { name:CountryCode.MT, dialCode: CountryDialCode.MT, flag: CountryFlag.MT },
    { name:CountryCode.EE, dialCode: CountryDialCode.EE, flag: CountryFlag.EE },
    { name:CountryCode.LT, dialCode: CountryDialCode.LT, flag: CountryFlag.LT },
    { name:CountryCode.LV, dialCode: CountryDialCode.LV, flag: CountryFlag.LV },
    { name:CountryCode.PL, dialCode: CountryDialCode.PL, flag: CountryFlag.PL },
    { name:CountryCode.CZ, dialCode: CountryDialCode.CZ, flag: CountryFlag.CZ },
    { name:CountryCode.SK, dialCode: CountryDialCode.SK, flag: CountryFlag.SK },
    { name:CountryCode.HU, dialCode: CountryDialCode.HU, flag: CountryFlag.HU },
    { name:CountryCode.SI, dialCode: CountryDialCode.SI, flag: CountryFlag.SI },
    { name:CountryCode.RO, dialCode: CountryDialCode.RO, flag: CountryFlag.RO },
    { name:CountryCode.BG, dialCode: CountryDialCode.BG, flag: CountryFlag.BG },
    { name:CountryCode.HR, dialCode: CountryDialCode.HR, flag: CountryFlag.HR },
    { name:CountryCode.RS, dialCode: CountryDialCode.RS, flag: CountryFlag.RS },
    { name:CountryCode.ME, dialCode: CountryDialCode.ME, flag: CountryFlag.ME },
    { name:CountryCode.AL, dialCode: CountryDialCode.AL, flag: CountryFlag.AL },
    { name:CountryCode.MK, dialCode: CountryDialCode.MK, flag: CountryFlag.MK },
    { name:CountryCode.BA, dialCode: CountryDialCode.BA, flag: CountryFlag.BA },
    { name:CountryCode.XK, dialCode: CountryDialCode.XK, flag: CountryFlag.XK },
    { name:CountryCode.UA, dialCode: CountryDialCode.UA, flag: CountryFlag.UA },
    { name:CountryCode.BY, dialCode: CountryDialCode.BY, flag: CountryFlag.BY },
    { name:CountryCode.MD, dialCode: CountryDialCode.MD, flag: CountryFlag.MD },
    { name:CountryCode.RU, dialCode: CountryDialCode.RU, flag: CountryFlag.RU },
    { name:CountryCode.AM, dialCode: CountryDialCode.AM, flag: CountryFlag.AM },
    { name:CountryCode.AZ, dialCode: CountryDialCode.AZ, flag: CountryFlag.AZ },
    { name:CountryCode.GE, dialCode: CountryDialCode.GE, flag: CountryFlag.GE },
    { name:CountryCode.KZ, dialCode: CountryDialCode.KZ, flag: CountryFlag.KZ },
    { name:CountryCode.TJ, dialCode: CountryDialCode.TJ, flag: CountryFlag.TJ },
    { name:CountryCode.TM, dialCode: CountryDialCode.TM, flag: CountryFlag.TM },
    { name:CountryCode.UZ, dialCode: CountryDialCode.UZ, flag: CountryFlag.UZ },
    { name:CountryCode.TR, dialCode: CountryDialCode.TR, flag: CountryFlag.TR },
    { name:CountryCode.CN, dialCode: CountryDialCode.CN, flag: CountryFlag.CN },
    { name:CountryCode.JP, dialCode: CountryDialCode.JP, flag: CountryFlag.JP },
    { name:CountryCode.KR, dialCode: CountryDialCode.KR, flag: CountryFlag.KR },
    { name:CountryCode.VN, dialCode: CountryDialCode.VN, flag: CountryFlag.VN },
    { name:CountryCode.IN, dialCode: CountryDialCode.IN, flag: CountryFlag.IN },
    { name:CountryCode.PK, dialCode: CountryDialCode.PK, flag: CountryFlag.PK },
    { name:CountryCode.BD, dialCode: CountryDialCode.BD, flag: CountryFlag.BD },
    { name:CountryCode.NP, dialCode: CountryDialCode.NP, flag: CountryFlag.NP },
    { name:CountryCode.LK, dialCode: CountryDialCode.LK, flag: CountryFlag.LK },
    { name:CountryCode.MM, dialCode: CountryDialCode.MM, flag: CountryFlag.MM },
    { name:CountryCode.TH, dialCode: CountryDialCode.TH, flag: CountryFlag.TH },
    { name:CountryCode.LA, dialCode: CountryDialCode.LA, flag: CountryFlag.LA },
    { name:CountryCode.KH, dialCode: CountryDialCode.KH, flag: CountryFlag.KH },
    { name:CountryCode.MY, dialCode: CountryDialCode.MY, flag: CountryFlag.MY },
    { name:CountryCode.SG, dialCode: CountryDialCode.SG, flag: CountryFlag.SG },
    { name:CountryCode.ID, dialCode: CountryDialCode.ID, flag: CountryFlag.ID },
    { name:CountryCode.TL, dialCode: CountryDialCode.TL, flag: CountryFlag.TL },
    { name:CountryCode.PH, dialCode: CountryDialCode.PH, flag: CountryFlag.PH },
    { name:CountryCode.AU, dialCode: CountryDialCode.AU, flag: CountryFlag.AU },
    { name:CountryCode.NZ, dialCode: CountryDialCode.NZ, flag: CountryFlag.NZ },
    { name:CountryCode.FJ, dialCode: CountryDialCode.FJ, flag: CountryFlag.FJ },
    { name:CountryCode.TO, dialCode: CountryDialCode.TO, flag: CountryFlag.TO },
    { name:CountryCode.WS, dialCode: CountryDialCode.WS, flag: CountryFlag.WS },
    { name:CountryCode.TV, dialCode: CountryDialCode.TV, flag: CountryFlag.TV },
    { name:CountryCode.SB, dialCode: CountryDialCode.SB, flag: CountryFlag.SB },
    { name:CountryCode.PG, dialCode: CountryDialCode.PG, flag: CountryFlag.PG },
    { name:CountryCode.NR, dialCode: CountryDialCode.NR, flag: CountryFlag.NR },
    { name:CountryCode.VU, dialCode: CountryDialCode.VU, flag: CountryFlag.VU },
    { name:CountryCode.NC, dialCode: CountryDialCode.NC, flag: CountryFlag.NC },
    { name:CountryCode.PF, dialCode: CountryDialCode.PF, flag: CountryFlag.PF },
    { name:CountryCode.CK, dialCode: CountryDialCode.CK, flag: CountryFlag.CK },
    { name:CountryCode.NU, dialCode: CountryDialCode.NU, flag: CountryFlag.NU },
    { name:CountryCode.WF, dialCode: CountryDialCode.WF, flag: CountryFlag.WF },
    { name:CountryCode.PN, dialCode: CountryDialCode.PN, flag: CountryFlag.PN },
    { name:CountryCode.TK, dialCode: CountryDialCode.TK, flag: CountryFlag.TK },
    { name:CountryCode.FM, dialCode: CountryDialCode.FM, flag: CountryFlag.FM },
    { name:CountryCode.MH, dialCode: CountryDialCode.MH, flag: CountryFlag.MH },
    { name:CountryCode.PW, dialCode: CountryDialCode.PW, flag: CountryFlag.PW },
    { name:CountryCode.KP, dialCode: CountryDialCode.KP, flag: CountryFlag.KP },   
  ];
  